### ISSUE TITLE
Create base plate options for the V0 and Switchwire

### ISSUE THREAD

**Issue by VinnyCordeiro** [rdmullett/voron_serial_plate#3]
Voron 0 printers uses 15 mm × 15 mm aluminum profiles, while the Switchwire uses 30 mm × 30 mm or 30 mm × 60 mm profiles. There's a need for new base plates in order to fit these profiles, as right now these only fits 20 mm × 20 mm profiles.

**Comment by rdmullett** [comment]
@VinnyCordeiro You know, when I initially did this I forgot to create an issue for this specific issue, but I was aware of this. I used the base model from the enclosure clips to generate the current design. Do you happen to know off the top of your head whether the V0 and VS have equivalent clips for enclosures that I could modify to use?

**Comment by VinnyCordeiro** [comment]
Switchwire is a bed slinger, so I don't believe it has an enclosure _per se_ on the printer itself (think like an Ender 3 or a Prusa printer), but the V0 do have some clips.

However, now that you mention it, I don't believe that there is space on the front of the V0 (be it the original one or the 0.1) to attach a nameplate. The best option I devise would be modify the front door upper hinge piece: 

* V0:
  * 2mm door panel: https://github.com/VoronDesign/Voron-0/blob/Voron0.0/VORON-0/STLs/V0_Panel_Mounting/For_2mm_Panels/2mm_Hinge_Top_A_x1.STL
  * 2.5mm door panel: https://github.com/VoronDesign/Voron-0/blob/Voron0.0/VORON-0/STLs/V0_Panel_Mounting/For_2.5mm_Panels/2point5mm_Hinge_Top_A_x1.STL
  * 3mm door panel: https://github.com/VoronDesign/Voron-0/blob/Voron0.0/VORON-0/STLs/V0_Panel_Mounting/For_3mm_Panels/3mm_Hinge_Top_A_x1.stl
* V0.1:
  * 2mm door panel: https://github.com/VoronDesign/Voron-0/blob/Voron0.1/STLs/Panel_Mounting/For_2mm_Panels/2mm_Hinge_Top_A_x1.STL
  * 2.5mm door panel: https://github.com/VoronDesign/Voron-0/blob/Voron0.1/STLs/Panel_Mounting/For_2.5mm_Panels/2point5mm_Hinge_Top_A_x1.STL
  * 3mm door panel: https://github.com/VoronDesign/Voron-0/blob/Voron0.1/STLs/Panel_Mounting/For_3mm_Panels/3mm_Hinge_Top_A_x1.stl

And after all that, I think this is more work than it's worth to maintain. The files seems unchanged between the revisions, but it's still 3 files to change. But that's me, what do you think about it?

**Comment by rdmullett** [comment]
@VinnyCordeiro Someone from thingiverse actually took the time to get a V0 remix created, so I've added it to the project in 505d31e and copied a 2nd scad script that will work with the V0 plates. I'm working on getting it added to the bot now, but I'm closing this issue for now since it is included on this project and the remaining work is on the actual bot itself.

**Comment by VinnyCordeiro** [comment]
> 
> 
> @VinnyCordeiro Someone from thingiverse actually took the time to get a V0 remix created, so I've added it to the project in [505d31e](https://github.com/rdmullett/voron_serial_plate/commit/505d31e4d42a64e8822a9812dbfb0007574be0e3) and copied a 2nd scad script that will work with the V0 plates. I'm working on getting it added to the bot now, but I'm closing this issue for now since it is included on this project and the remaining work is on the actual bot itself.

I saw that earlier on the Voron Discord, quite ingenious solution, I must say.
